### ISSUE TITLE
Add gatsby sitemap plugin

### ISSUE THREAD

**Issue by TamimiGitHub** [SolaceDev/solace-dev-tutorials#57]

**Comment by blainehussey** [comment]
Hi @TamimiGitHub,
Just took a look and it seems like the sitemap plugin is working, just ran a `npm build`, looked in `/public/sitemap/*` (as it's only generated on production) and I'm getting the following below. Here's hoping this will increase our SEO even more 🤞🏻 

`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xmlns:video="http://www.google.com/schemas/sitemap-video/1.1"><url><loc>https://tutorials.solace.dev/tanzu/ldap/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/tanzu/secure-session/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/tanzu/java-app/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/tanzu/spring-cloud-autoconf-java/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/tanzu/spring-cloud/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/tanzu/spring-cloud-autoconf-jms/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/tanzu/spring-cloud-autoconf-jndi/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/tanzu/tcp-routes-mqtt/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/spring/spring-boot-autoconfigure/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/spring/spring-cloud-stream/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/semp/generate-semp-client-lib/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/semp/curl/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/semp/java-client/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/semp/messagevpn-with-queue-ruby/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/semp/messagevpn-with-queue-java/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/rest-messaging/publish-subscribe/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/semp/messagevpn-with-queue-python/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/openmama/hello-world/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/openmama/publish-subscribe/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/nodejs-amqp/persistence-with-queues/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/openmama/installation-linux/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/nodejs-amqp/topic-to-queue-mapping/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/nodejs/confirmed-delivery/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/nodejs-amqp/confirmed-delivery/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/nodejs/persistence-with-queues/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/jms/confirmed-delivery/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/nodejs/topic-to-queue-mapping/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/nodejs/publish-subscribe/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/nodejs/request-reply/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/jms/request-reply/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/jms/publish-subscribe/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/jms/topic-to-queue-mapping/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/jms/using-external-jndi/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/jcsmp/browsing-queues/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/jms/using-jndi/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/jms/persistence-with-queues/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/jcsmp/message-selectors/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/jcsmp/confirmed-delivery/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/jcsmp/message-replay/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/jcsmp/active-flow-indication/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/jcsmp/publish-subscribe/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/jcsmp/persistence-with-queues/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/jcsmp/topic-to-queue-mapping/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/jcsmp/request-reply/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/jcsmp/ttl-and-dmq/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/jcsmp/transactions/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/javascript/confirmed-delivery/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/javascript/active-consumer-indication/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/javascript/dte-consumer/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/javascript/persistence-with-queues/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/javascript/message-replay/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/javascript/topic-to-queue-mapping/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/javascript/publish-subscribe/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/java-mqtt-paho/confirmed-delivery/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/javarto/publish-subscribe/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/javascript/request-reply/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/java-mqtt-paho/persistence-with-queues/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/java-mqtt-paho/publish-subscribe/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/java-mqtt-paho/request-reply/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/java-mqtt-paho/topic-to-queue-mapping/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/java-amqp-qpid-jms2/persistence-with-queues/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/java-amqp-qpid-jms2/durable-topic-subscriber/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/java-amqp-qpid-jms2/publish-subscribe/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/java-amqp-qpid-jms2/confirmed-delivery/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/java-amqp-qpid-jms2/request-reply/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/java-amqp-qpid-jms1/confirmed-delivery/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/java-amqp-qpid-jms2/topic-to-queue-mapping/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/java-amqp-qpid-jms1/request-reply/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/java-amqp-qpid-jms1/topic-to-queue-mapping/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/java-amqp-qpid-jms1/publish-subscribe/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/java-amqp-qpid-jms1/persistence-with-queues/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/dotnet/publish-subscribe/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/dotnet/persistence-with-queues/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/dotnet/confirmed-delivery/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/dotnet/request-reply/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/dotnet/topic-to-queue-mapping/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/c/message-replay/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/c/publish-subscribe/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/c/persistence-with-queues/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/c/request-reply/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/c/topic-to-queue-mapping/</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/spring</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/tanzu</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/rest-messaging</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/python</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/semp</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/nodejs-amqp</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/openmama</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/nodejs</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/jcsmp</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/jms</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/javarto</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/javascript</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/java-mqtt-paho</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/java-amqp-qpid-jms2</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/java</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/java-amqp-qpid-jms1</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/dotnet</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/c</loc><changefreq>daily</changefreq><priority>0.7</priority></url><url><loc>https://tutorials.solace.dev/</loc><changefreq>daily</changefreq><priority>0.7</priority></url></urlset>`
