### ISSUE TITLE
Change JavaRTO logo from "Java" to "JNI"

### ISSUE THREAD

**Issue by TamimiGitHub** [SolaceDev/solace-dev-tutorials#68]
See screenshots below
![image (1)](https://user-images.githubusercontent.com/6826053/122819825-eef05a80-d2a8-11eb-8348-bf081676fb47.png)
![image (2)](https://user-images.githubusercontent.com/6826053/122819829-f0ba1e00-d2a8-11eb-808f-0b622c4f6280.png)

**Comment by aaron-613** [comment]
Not sure which exact font is used for the logo...  close?  https://fontslogo.com/java-logo-font/

From Oracle branding document:
![image](https://user-images.githubusercontent.com/7603332/123037524-634e0980-d421-11eb-92d8-0d8ff2ebf097.png)


For the mockup above, I just used Open Sans.  If you copy the "J" from the Java logo and just use "NI" from Open Sans, I'm sure it would look ok..?

**Comment by blainehussey** [comment]
@TamimiGitHub and @aaron-613 - Please let me know if I'm missing anything for this issue.

<img width="1158" alt="Screen Shot 2021-06-30 at 11 18 00 AM" src="https://user-images.githubusercontent.com/6960616/123988950-710e0c80-d996-11eb-931b-a648a3d3a803.png">

**Comment by Mrc0113** [comment]
LGTM :) 
I'll ping Aaron via slack

**Comment by TamimiGitHub** [comment]
🚢 it!

**Comment by aaron-613** [comment]
Pinged Blaine on Slack, but guess I'll add comments here for traceability.  I think the serif font chosen for the "NI" is very obviously different than the "J", and doesn't match anything else on the page:

![image](https://user-images.githubusercontent.com/7603332/124094087-07235f00-da8b-11eb-94ec-75eea15a1891.png)


But weirdly, the post Blaine made above where he circled in red the logo, it looks good!?  https://user-images.githubusercontent.com/6960616/123988950-710e0c80-d996-11eb-931b-a648a3d3a803.png

So is there some issue with fonts I'm having locally?  Is it a graphic, or dynamically loaded or something..?

**Comment by blainehussey** [comment]
Thanks for reviewing @aaron-613, could be some issue with the SVG serving it. I did use Open Sans as requested and it did turn out good on my end but perhaps you don't have that font installed on your end. I probably need to re-export so the Ni is not as a font but traced as a layer.
