### ISSUE TITLE
Some wrong text on some tutorial subpages

### ISSUE THREAD

**Issue by aaron-613** [SolaceDev/solace-dev-tutorials#74]
On the Python tutorials page, it says "Spring".  Just correct to Python:

![image](https://user-images.githubusercontent.com/7603332/124694074-2995fc00-df13-11eb-8a9e-0c1c81c183c5.png)
https://tutorials.solace.dev/python

On the SEMP page, it talks about "key message exchange patterns" and also "sending and receiving with SEMP":
![image](https://user-images.githubusercontent.com/7603332/124694262-78dc2c80-df13-11eb-8cfe-5e76b50ba8c6.png)
https://tutorials.solace.dev/semp

That is incorrect, since this is a configuration/management API.

The text at the top should say something like: "These tutorials will help you get started managing and configuring your Solace PubSub+ event broker."  Or: "SEMP is a RESTful management API for configuring and administrating your Solace PubSub+ event broker".  I like the 2nd better, makes it clear what SEMP is.

Then the subheader "key message exchange patters", below "Tutorials" can probably just be removed.

**Comment by Mrc0113** [comment]
Hey @blainehussey, can you tackle these when you get a chance?

**Comment by blainehussey** [comment]
On it @Mrc0113 and @aaron-613, thanks for flagging these.
